spring.application.name=authorization-server

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=keyserver

# Ensure no conflicting HTTP configuration is enabled
server.http.enabled=false
